### ISSUE TITLE
A Bug of Most Serious Sort!

### ISSUE THREAD

**Issue by lisefromberlin** [konstatoivanen/konstatoivanen.github.io#1]
I was minding my own business when, all of a sudden, I came across this:

![Capture](https://user-images.githubusercontent.com/45340812/116418467-d6356c80-a844-11eb-9ca8-386b40d7b1de.PNG)

My heart sank. A mistake! Shell-shocked, I rushed here to open this ticket.

Plz fix

**Comment by konstatoivanen** [comment]
Resolved
